export const constants = {
  LEGAL_ENTITY: 'Legal Entity Name',
  ENTER_LEGAL_ENTITY: 'Enter Your Company Name',
  ENTER_FULL_NAME: 'Enter Your Full Name',
  PROJECT_NAME: 'Project Name',
  EMAIL: 'Email Address',
  ENTER_EMAIL: 'Enter Your Email Address',
  FULL_NAME: 'Full Name',
  ROLE: 'Role',
  DATE: 'Date',
  ENTER_ROLE: 'Enter Your Role',
  ENTER_PROJECT_NAME: 'Enter Project Name',
  ENTER_DOB: 'Enter Date of Birth',
  ENTER_OWNERSHIP: 'Enter Ownership Percentage',
  ENTER_COUNTRY: 'Enter Country',
  ENTER_REGION: 'Enter Region',
  CATEGORY: 'Business Category',
  REGISTRATION_NO: 'Legal Entity Registration No',
  WEBSITE: 'Website',
  COUNTRY: 'Country of Incorporation',
  PRODUCTS: 'Products Enabled',
  TOKEN: 'Token Address if exists',
  DESCRIPTION: 'Product Description',
  NOTES: 'Additional Notes',
  BUY: 'Buy',
  SELL: 'Sell',
  SUBSCRIBE: 'Subscribe',
  YES: 'Yes',
  NO: 'No',
  NA: 'N/A',
  PRODUCT_CUSTODIAL_OR_NOT: 'Is the product Non-Custodial or Custodial',
  CUSTODIAL: 'Custodial',
  NON_CUSTODIAL: 'Non-Custodial',
  ACCESS_CONTROL_FUNDS: 'Do Users have full access or control of their funds'
};
