export const posthogEvents = {
  SELECT_COIN: 'select_coin',
  SELECT_FIAT: 'select_fiat',
  AMOUNT_ADDED: 'amount_added',
  STAKE_COIN: 'stake_select_coin',
  SELECT_COUNTRY: 'select_country',
  PRICE_COMPARE: 'price_compare',
  PAYMENT_METHOD: 'select_payment_method',
  PROVIDER: 'select_provider',
  TWO_STEPS: '2_steps',
  SWAP_SEND_COIN: 'swap_send_coin_selected',
  SWAP_RECEIVE_COIN: 'swap_receive_coin_selected',
  CLICK_SWAP_BUTTON: 'click_swap',
  CLICK_BUY_BUTTON: 'click_buy',
  CLICK_SELL_BUTTON: 'click_sell',
  CLICK_STAKE_BUTTON: 'click_stake',
  SELECT_SWAP_CHAIN: 'select_swap_chain',
  SELECT_SWAP_COIN: 'select_swap_coin',
  TRADE_HISTORY: 'trade_history',
  RIP_POINTS: 'rip_points',
  REFERRAL: 'referrals',
  SETTINGS: 'settings',
  MY_PROFILE: 'my_profile',
  MY_WALLET: 'my_wallet',
  LOG_OUT: 'log_out'
};
